name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks ${{ github.actor }}, for your help keeping our issues up to date!"
        pr-message: "Hello ${{ github.actor }}, this is your first pull request, Thanks for your contribution"
